### PR TITLE
Core molecule handling

### PR DESCRIPTION
**Pull request by ssande7**
**Summary**

This introduces `fix property/molecule` as a centralised handler for per-molecule data. Other fixes/computes can register per-molecule arrays/vectors using the `atom->propert_molecule->register_permolecule` function. Those arrays can be addressed based on atom `i` using `atom->molecule[i]-1`.

Also removes references to "chunk" nomenclature in favour of "mol".

**Author(s)**

Stephen, Shern.

**Implementation Notes**

FPM grows per-molecule arrays during setup phase currently, so some extra handling will be needed for things like GCMC.

It calculates molecular masses and centers of mass internally in the pre-force step so that they're up to date for pair force calculations.

Currently masses are calculated during setup, so it's assumed they won't change during a run (again, will need updating for things like GCMC).

CoM is currently updated every timestep, and for all molecules in the system. It would be nice to add some sort of registration procedure where styles that require molecular mass/CoM can register their requirement, along with which groups they require it for, so then FPM can calculate only on the necessary steps, and skip unneeded molecules. In this case, we should probably warn about calculations that include some but not all atoms within a molecule.

To avoid breaking builds that don't use the MOL-SLLOD package, `FixPropertyMolecule` is currently in the main `src/` directory. Alternatively, we could look into using a dummy implementation, but I think the current situation is probably better suited in terms of allowing other parts of the code to interface with FPM in future.

### CODE REVIEW

**Comment by ssande7** [comment]
Currently has divergent dynamics for monoatoms unit test. Output looks reasonable though, so not sure what changed, or whether it's actually broken... Offending commit comes before the merge with fpm_debug (need to edit unit test to prevent it from skipping the required one since pair_lj_cut_chunk was removed).

Passes unit test with all molecules within reasonable floating point error.

**Comment by ssande7** [comment]
The disagreement appears to be coming from the switch away from `pair_style lj/cut/chunk` to `pair_style lj/cut`. In the former, pairs were skipped if an atom wasn't part of a molecule, so pair-wise interactions between single atoms were erroneously excluded (see `pair_lj_cut_chunk.cpp:135`). Considering that the unit test without any lone atoms passes, I think it's safe to update the monoatoms test based on the new dynamics. @srtee do you agree?

**Comment by srtee** [comment]
> The disagreement appears to be coming from the switch away from `pair_style lj/cut/chunk` to `pair_style lj/cut`. In the former, pairs were skipped if an atom wasn't part of a molecule, so pair-wise interactions between single atoms were erroneously excluded (see `pair_lj_cut_chunk.cpp:135`). Considering that the unit test without any lone atoms passes, I think it's safe to update the monoatoms test based on the new dynamics. @srtee do you agree?

I will run a comparison between `pair_style lj/cut/chunk` and `pair_style lj/cut` on the unit test configurations and input files but with `fix nvt` instead of deforming box, and for two scenarios -- mixture of monoatoms and diatomic molecules, and purely monoatoms. If they are different then I will update the monoatoms test and merge the commit. Should be done by this time tomorrow if not earlier.

**Comment by ssande7** [comment]
Shern's tests showed 0 energy for all-atomic systems with `pair lj/cut/chunk`, confirming that the old monoatoms unit test had incorrect dynamics. With that sorted, I think this is ready to merge.

**Comment by ssande7** [comment]
@emilyviolet Handling of single atom velocity updates is now fixed as discussed, along with a bit of minor cleanup of old comments and includes. I don't think any of the remaining `TODO` notes are blocking, but let me know if you come across anything.

Edit: one other thing to check - do we need to override `deform(int)` in `FixPropertyMolecule` to map `com` to and from lamda coordinates? I think we're probably ok without it for now, but it might be needed to stabilise FPM as a general molecule API for other/future parts of LAMMPS.

**Review by emilyviolet — APPROVED** [review]
Looks good to me, happy to merge this now

**Pull request merged**
